# Generated by Django 4.1.5 on 2023-02-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=50)),
                ("salary", models.PositiveIntegerField()),
                ("experience", models.PositiveIntegerField()),
            ],
        ),
    ]
